/**
 * Duuka — development seed.
 *
 * These are DEVELOPMENT FIXTURES for reviewing the product, clearly labeled as
 * such in the repository. Fixture users have demo passwords and 0000xxx phone
 * numbers. Production must never run this seed.
 *
 * Run: bun scripts/seed.ts
 */
import { PrismaClient } from '@prisma/client'
import { randomBytes, scryptSync } from 'node:crypto'
import { LISTING_ACTIVE_DAYS } from '../src/lib/constants'

const db = new PrismaClient()

function hashPassword(password: string): string {
  const salt = randomBytes(16).toString('hex')
  return `${salt}:${scryptSync(password, salt, 64).toString('hex')}`
}

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000)

interface SeedListing {
  ownerIdx: number
  type: 'OFFER' | 'REQUEST'
  title: string
  description: string
  category: string
  price: number | null
  compareAtPrice?: number | null // optional "was" price — renders as a discount
  currency?: string
  priceNegotiable?: boolean
  unit: string | null
  quantity: number | null
  county: string
  country: string
  area: string | null
  refreshedHoursAgo: number
  views: number
  status?: string
  expiresInDaysOverride?: number
  photo?: string // /uploads/seed/... — generated by scripts/generate-seed-images.mjs
}

const users = [
  // Uganda — the launch market.
  { name: 'Nakato Fresh Produce', phone: '+256772123456', country: 'UG', profile: { businessName: 'Nakato Fresh Produce', photoUrl: '/uploads/seed/shop-nakato.png', category: 'farm-produce', county: 'Kampala', area: 'Nakasero', description: 'Fresh matooke, tomatoes and onions from farms around Mpigi. Wholesale and retail.', hours: 'Daily, 6am–6pm' } },
  { name: 'Kampalamart Scrap Dealers', phone: '+256776123456', country: 'UG', profile: { businessName: 'Kampalamart Scrap Dealers', photoUrl: '/uploads/seed/shop-kampalamart.png', category: 'scrap-recyclables', county: 'Kampala', area: 'Kisenyi', description: 'We buy copper, brass, aluminium and plastics. Honest weighing on a certified scale, same-day payment.', hours: 'Mon–Sat, 7am–5pm' } },
  { name: 'Jinja Hardware Centre', phone: '+256758123456', country: 'UG', profile: { businessName: 'Jinja Hardware Centre', photoUrl: '/uploads/seed/shop-jinja-hardware.png', category: 'hardware-building', county: 'Jinja', area: 'Kimaka', description: 'Cement, roofing sheets, steel bars and general hardware at friendly prices.', hours: 'Mon–Sat, 8am–6pm' } },
  // Tanzania.
  { name: 'Dodoma Agri Supplies', phone: '+255712345678', country: 'TZ', profile: { businessName: 'Dodoma Agri Supplies', photoUrl: '/uploads/seed/shop-dodoma-agri.png', category: 'farm-produce', county: 'Dodoma', area: 'Chang’ombe', description: 'Sunflower oil, beans and maize supplied to shops and institutions around Dodoma.', hours: 'Mon–Sat, 7am–4pm' } },
  // Kenya (existing fixtures kept for regional coverage).
  { name: 'Jomo Scrap Traders', phone: '+254712000001', country: 'KE', profile: { businessName: 'Jomo Scrap Traders', photoUrl: '/uploads/seed/shop-jomo-scrap.png', category: 'scrap-recyclables', county: 'Nairobi', area: 'Gikomba', description: 'We buy and grade non-ferrous scrap. Same-day payment on verified weights.', hours: 'Mon–Sat, 7am–5pm' } },
  { name: 'Pendo Flour Millers', phone: '+254712000002', country: 'KE', profile: { businessName: 'Pendo Flour Millers', photoUrl: '/uploads/seed/shop-pendo-flour.png', category: 'food-groceries', county: 'Nakuru', area: 'Free Area', description: 'Millers of wheat and maize flour for shops and institutions.', hours: 'Mon–Fri, 8am–4pm' } },
  { name: 'Mama Amina Chapati Supplies', phone: '+254712000003', country: 'KE', profile: { businessName: 'Mama Amina Chapati Supplies', photoUrl: '/uploads/seed/shop-mama-amina.png', category: 'food-groceries', county: 'Mombasa', area: 'Kongowea', description: 'Wholesale supplies for chapati and mandazi vendors.', hours: 'Daily, 6am–2pm' } },
  { name: 'Kisumu Fresh Produce', phone: '+254712000004', country: 'KE', profile: { businessName: 'Kisumu Fresh Produce', photoUrl: '/uploads/seed/shop-kisumu-fresh.png', category: 'farm-produce', county: 'Kisumu', area: 'Ahero', description: 'Direct from farms around Ahero. Bulk buyers welcome.', hours: 'Mon–Sat, 6am–6pm' } },
]

const listings: SeedListing[] = [
  // Uganda (UGX).
  { ownerIdx: 0, type: 'OFFER', title: 'Fresh matooke, wholesale bunches', photo: '/uploads/seed/listing-matooke.png', description: 'Green matooke straight from Mpigi farms, hand-picked this morning. Bunches from 8kg up. Bring your own transport or we arrange delivery within Kampala.', category: 'farm-produce', price: 18000, compareAtPrice: 22000, currency: 'UGX', unit: 'bunch', quantity: 250, county: 'Kampala', country: 'UG', area: 'Nakasero', refreshedHoursAgo: 3, views: 41 },
  { ownerIdx: 0, type: 'OFFER', title: 'Grade A eggs in crates of 30', photo: '/uploads/seed/listing-eggs-ug.png', description: 'Fresh grade A eggs collected daily from our layers in Mukono. Sold per crate of 30. Bring your own crates or buy ours at cost.', category: 'farm-produce', price: 12000, currency: 'UGX', unit: 'crate', quantity: 180, county: 'Kampala', country: 'UG', area: null, refreshedHoursAgo: 6, views: 27 },
  { ownerIdx: 1, type: 'OFFER', title: 'Copper scrap, 99.5% clean', photo: '/uploads/seed/listing-copper.png', description: 'Clean copper wire scrap, no insulation, sorted and ready. Weighing done on a certified platform scale in front of the seller. Collection from our Kisenyi yard.', category: 'scrap-recyclables', price: 20000, currency: 'UGX', unit: 'kg', quantity: 600, county: 'Kampala', country: 'UG', area: 'Kisenyi', refreshedHoursAgo: 2, views: 55 },
  { ownerIdx: 1, type: 'REQUEST', title: 'Aluminium scrap wanted — monthly bulk', photo: '/uploads/seed/listing-aluminium.png', description: 'Buying aluminium scrap monthly: ingots, sheets, castings. Pay per kg on graded weight, same-day mobile money payment. Contact with your available quantity and location.', category: 'scrap-recyclables', price: 6500, currency: 'UGX', unit: 'kg', quantity: 1500, county: 'Kampala', country: 'UG', area: null, refreshedHoursAgo: 20, views: 14 },
  { ownerIdx: 2, type: 'OFFER', title: 'Cement 42.5N, 50kg bags', photo: '/uploads/seed/listing-cement.png', description: 'Tororo cement 42.5N in 50kg bags, stored dry in our Kimaka godown. Discount above 100 bags, delivery around Jinja town available.', category: 'hardware-building', price: 32000, compareAtPrice: 36000, currency: 'UGX', priceNegotiable: true, unit: 'bag', quantity: 900, county: 'Jinja', country: 'UG', area: 'Kimaka', refreshedHoursAgo: 30, views: 33 },
  { ownerIdx: 2, type: 'OFFER', title: 'Iron sheets 30 gauge, 3m', photo: '/uploads/seed/listing-iron-sheets.png', description: 'Pre-painted 30 gauge iron sheets, box profile, various colours in stock. Per piece price for 3 metre lengths. Delivery within Jinja and Iganga.', category: 'hardware-building', price: 38000, currency: 'UGX', unit: 'piece', quantity: 320, county: 'Jinja', country: 'UG', area: null, refreshedHoursAgo: 96, views: 19 },
  { ownerIdx: 0, type: 'REQUEST', title: 'Red onions wanted — weekly supply', photo: '/uploads/seed/listing-red-onions.png', description: 'Looking for a steady weekly supplier of red onions for our market stall, at least 300kg per week. Payment on delivery, Kampala Nakasero.', category: 'farm-produce', price: 5200, currency: 'UGX', unit: 'kg', quantity: 300, county: 'Kampala', country: 'UG', area: null, refreshedHoursAgo: 50, views: 9 },
  // Tanzania (TZS).
  { ownerIdx: 3, type: 'OFFER', title: 'Sunflower cooking oil, 20L', photo: '/uploads/seed/listing-sunflower-oil.png', description: 'Pure sunflower cooking oil in 20L jerricans, pressed in Dodoma. Ideal for vendors and institutions. Delivery around Dodoma municipality.', category: 'food-groceries', price: 58000, compareAtPrice: 65000, currency: 'TZS', unit: 'piece', quantity: 120, county: 'Dodoma', country: 'TZ', area: 'Chang’ombe', refreshedHoursAgo: 8, views: 22 },
  { ownerIdx: 3, type: 'OFFER', title: 'Dry maize grade 1, per kg', photo: '/uploads/seed/listing-maize.png', description: 'Grade 1 dry maize, moisture 13%, from this season harvest in Kongwa. Sold per kg or per tonne with weighing at our Chang’ombe store.', category: 'farm-produce', price: 950, currency: 'TZS', unit: 'kg', quantity: 15000, county: 'Dodoma', country: 'TZ', area: null, refreshedHoursAgo: 60, views: 47 },
  // Kenya (KES).
  { ownerIdx: 4, type: 'OFFER', title: 'Wheat flour premium, 50kg bags', photo: '/uploads/seed/listing-wheat-flour.png', description: 'Baking-grade wheat flour, milled this week. Packed in 50kg bags on pallets. Delivery within Nakuru town free for orders above 20 bags.', category: 'food-groceries', price: 4800, currency: 'KES', priceNegotiable: true, unit: 'bag', quantity: 120, county: 'Nakuru', country: 'KE', area: 'Free Area', refreshedHoursAgo: 24, views: 21 },
  { ownerIdx: 5, type: 'OFFER', title: 'Fresh eggs in crates', photo: '/uploads/seed/listing-eggs-ke.png', description: 'Grade A fresh eggs collected daily. Sold per crate of 30. Bring your own crates or buy ours at cost.', category: 'farm-produce', price: 420, currency: 'KES', unit: 'crate', quantity: 300, county: 'Kisumu', country: 'KE', area: 'Ahero', refreshedHoursAgo: 4, views: 18 },
  { ownerIdx: 6, type: 'REQUEST', title: 'Cooking oil 20L — weekly supply needed', photo: '/uploads/seed/listing-oil-mombasa.png', description: 'Looking for a consistent weekly supplier of cooking oil in 20L jerricans for our chapati vendors. Payment on delivery, Mombasa island and Kongowea.', category: 'food-groceries', price: 5300, currency: 'KES', unit: 'piece', quantity: 15, county: 'Mombasa', country: 'KE', area: 'Kongowea', refreshedHoursAgo: 72, views: 8 },
  { ownerIdx: 4, type: 'OFFER', title: 'Second-hand clothes bales, mixed', photo: '/uploads/seed/listing-clothes-bales.png', description: 'Original mixed bales from our imports, unopened. Per bale price for ladies, gents and children mixes. Opening of bales allowed before payment.', category: 'textiles-clothing', price: 6200, currency: 'KES', priceNegotiable: true, unit: 'bale', quantity: 40, county: 'Nairobi', country: 'KE', area: 'Toi Market', refreshedHoursAgo: 48, views: 63 },
  { ownerIdx: 7, type: 'OFFER', title: 'Raw milk, chilled same-day', photo: '/uploads/seed/listing-milk.png', description: 'Fresh raw milk from our cooperative members, chilled at collection point. Sold per litre in 50 litre cans. Early morning collection recommended.', category: 'livestock-feed', price: 65, currency: 'KES', unit: 'litre', quantity: 900, county: 'Kisumu', country: 'KE', area: 'Ahero', refreshedHoursAgo: 7, views: 52 },
  { ownerIdx: 6, type: 'OFFER', title: 'Charcoal 50kg sacks, acacia', photo: '/uploads/seed/listing-charcoal.png', description: 'Hardwood acacia charcoal, long burning, packed in 50kg sacks. Delivery for 10 sacks and above within Mombasa.', category: 'home-kitchen', price: 3800, currency: 'KES', unit: 'sack', quantity: 80, county: 'Mombasa', country: 'KE', area: 'Kongowea', refreshedHoursAgo: 240, views: 39, status: 'FULFILLED' },
  { ownerIdx: 5, type: 'OFFER', title: 'Firewood bundles for lenders', photo: '/uploads/seed/listing-firewood.png', description: 'Split firewood bundles, dry eucalyptus. Ideal for institutions and ovens. Price per bundle of about 20kg.', category: 'other', price: 350, currency: 'KES', unit: 'bunch', quantity: 500, county: 'Nakuru', country: 'KE', area: 'Free Area', refreshedHoursAgo: 768, views: 11, expiresInDaysOverride: -1 },
]

const savedSearches = [
  { userIdx: 0, name: 'Copper scrap in Kampala', query: { q: 'copper', county: 'Kampala' } },
  { userIdx: 4, name: 'Maize offers', query: { q: 'maize', type: 'OFFER' as const } },
]

async function main() {
  console.log('Seeding Duuka development fixtures…')
  await db.notification.deleteMany()
  await db.savedSearch.deleteMany()
  await db.listing.deleteMany()
  await db.businessProfile.deleteMany()
  await db.session.deleteMany()
  await db.user.deleteMany()

  const createdUsers: { id: string; phone: string }[] = []
  for (const u of users) {
    const user = await db.user.create({
      data: { name: u.name, phone: u.phone, country: u.country, passwordHash: hashPassword('demo1234') },
    })
    await db.businessProfile.create({ data: { userId: user.id, phone: u.phone, whatsapp: u.phone, verified: false, ...u.profile } })
    createdUsers.push(user)
  }

  for (const l of listings) {
    const refreshedAt = hoursAgo(l.refreshedHoursAgo)
    const expiresAt = new Date(refreshedAt.getTime() + (l.expiresInDaysOverride !== undefined ? l.expiresInDaysOverride : LISTING_ACTIVE_DAYS) * 86_400_000)
    const searchText = `${l.title} ${l.description} ${l.category} ${l.area ?? ''} ${l.county}`.toLowerCase().replace(/\s+/g, ' ').trim()
    await db.listing.create({
      data: {
        userId: createdUsers[l.ownerIdx].id,
        type: l.type,
        title: l.title,
        description: l.description,
        category: l.category,
        price: l.price,
        compareAtPrice: l.compareAtPrice ?? null,
        currency: l.currency ?? 'UGX',
        priceNegotiable: l.priceNegotiable ?? false,
        unit: l.unit,
        quantity: l.quantity,
        county: l.county,
        country: l.country,
        area: l.area,
        contactPhone: createdUsers[l.ownerIdx].phone,
        contactWhatsapp: createdUsers[l.ownerIdx].phone,
        photos: JSON.stringify(l.photo ? [l.photo] : []),
        status: l.status ?? 'ACTIVE',
        searchText,
        viewCount: l.views,
        publishedAt: refreshedAt,
        refreshedAt,
        expiresAt,
      },
    })
  }

  // Saved searches with honestly computed match counts (same rules as the API).
  for (const s of savedSearches) {
    const where: Record<string, unknown> = { status: 'ACTIVE' }
    if (s.query.q) where.searchText = { contains: s.query.q.toLowerCase() }
    if ('type' in s.query && s.query.type) where.type = s.query.type
    if ('county' in s.query && s.query.county) where.county = s.query.county
    const total = await db.listing.count({ where: where as never })
    await db.savedSearch.create({
      data: {
        userId: createdUsers[s.userIdx].id,
        name: s.name,
        queryJson: JSON.stringify(s.query),
        lastMatchCount: total,
        lastCheckedAt: new Date(),
      },
    })
    console.log(`  saved search "${s.name}": ${total} real matches`)
  }

  const counts = {
    users: await db.user.count(),
    listings: await db.listing.count(),
    savedSearches: await db.savedSearch.count(),
  }
  console.log('Seed complete:', counts)
  console.log('Fixture passwords are "demo1234" (development only).')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
